### ISSUE TITLE
Security Upgrade &  Front-end Optimization

### ISSUE THREAD

**Issue by salander0411** [lab798/aws-alexa-workshop-smarthome#3]
1. Remember to exclude all the credentials exposing, including but not limited to AKSK, clientID etc.
https://github.com/lab798/aws-alexa-workshop-smarthome/blob/master/docs/create-cup-client.md

1. Front-end: No remind response after binding or unbinding  
https://github.com/lab798/aws-alexa-workshop-ui

1. Redirect to main READ.me or next step after every step. 
I have updated [this page](https://github.com/lab798/aws-alexa-workshop-ui)
You may need to revise other pages.

1. I have updated the "either or" relationship between local deployment and amplify console.Please check here  https://github.com/lab798/aws-alexa-workshop-ui

**Comment by JoeShi** [comment]
fix 1 & 3, 4

**Comment by JoeShi** [comment]
fixed 2., please check
